import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [snippetText, setSnippetText] = useState("");
  const [allSnippetsText, setAllSnippetsText] = useState([]);
  const router = useRouter();

  const snippet = trpc.snippet.saveSnippet.useMutation();
  const allSnippets = trpc.snippet.getAllSnippets.useQuery();

  const handleSaveSnippet = async () => {
    const newSnippet = await snippet.mutateAsync({
      text: snippetText,
    })
    console.table(newSnippet);
    router.push('/snippets/${newSnippet.id}');
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="mb-4 text-4xl font-bold">Paste Bin Clone</h1>
        <p> Paste in a snippet of text </p>
        <textarea 
          onChange={(e) => setSnippetText(e.target.value)} 
          className="border shadow-md rounded m-3 p-2 w-1/3 h-48"
          value={snippetText}  
        />
        <button 
          className="p-2 rounded text-white bg-blue-500 hover:bg-blue-400"
          onClick={handleSaveSnippet}
        >
          Save
        </button>
        <h3
          className="mt-4 text-2xl font-bold"
        >
          All Snippets 
        </h3>
        <div
          className="flex flex-col"
        >
          {allSnippets.data?.map((snippet) => (
            <textarea
              key={snippet.id}
              className="border shadow-md rounded m-3 p-2 w-30 h-20"
              disabled
              value={snippet.text}
            />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
