import { useRouter } from 'next/router';
import React from 'react';
import Head from 'next/head';
import { trpc } from '../../utils/trpc';

const SnippetPage = () => {
  const router = useRouter();
  const id = router.query.id as string;

  const oneSnippet = trpc.snippet.getOneSnippet.useQuery({ id: id  });

  return (
    <>
      <Head>
        <title>Snippet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="mb-4 text-4xl font-bold">Snippet {id} </h1>
        <textarea
          className="border shadow-md rounded m-3 p-2 w-1/3 h-48"
          disabled
          value={oneSnippet.data?.text}
        />
      </main>
    </>
  );
}

export default SnippetPage;